{% set name = "types-typed-ast" %}
{% set version = "1.5.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-typed-ast-{{ version }}.tar.gz
  sha256: fdec308ed991c267969c12e31f2d4a8eb527540a3833a72eb0bd479b2554f360

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/typed_ast-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for typed-ast
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
